boilerplates-and-starter-kits.md
https://github.com/chentsulin/electron-react-boilerplate
=> Electron + React

redux-tutorials.md
This is tooting my own horn but no pride invested so shoot this down if it isn't a good fit. But I've used your list as a resource (thank you!), and missing some material focusing on middlewares on the list is what prompted me to write the post in the first place! :)
=> adding middlewares post link to redux tutorials

boilerplates-and-starter-kits.md
Add react-boilerplate to boilerplates-and-starter-kits.md
=> Add react-boilerplate

functional-programming.md
I've been trying to learn functional concepts in parallel with diving deep in Elixir and stumbled upon a great video series by funfunfunction about functional programming in JavaScript. The teaching is great, the videos are really entertaining.
This commit:
1. removed blank white space from the file (it's in my vim config)
2. Added a youtube series to the bottom of the list.
=> Added link to functional programming for video series by funfunfunction

react-tutorials.md
A friend recommended me this guide to start react and I'm about halfway through the book. It is a really cool and hands-on based approach that takes you step-by-step through creating a bigger application, great for the kind of developer that much like me needs to get their toes wet before gaining any kind of motivation to read a slightly more technical/documentation heavy text.
=> Adding Hacking with React

react-tutorials.md, webpack-tutorials.md
Updated to reflect the split state. Now it's two books/tutorials instead of one.
=> Update SurviveJS bits

README.md
=> Fix 'Awesome React' link

redux-side-effects.md
=> remove duplicate link

functional-programming.md
This is a talk I gave on functional programming basics in JS with ES6 syntax back in August.
=> Add talk on FP basics in JS

MobX-tutorials.md, README.md
I added some mobX introduction tutorials and mobX docs. I also modified readme.md to add the new mobX section
=> added mobX links

react-native.md
=> Added awesome react native education

redux-tutorials.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
=> Remove "work in progress" from Redux Book

static-typing.md
added React & Redux in TypeScript - Static Typing Guide - https://github.com/piotrwitek/react-redux-typescript-guide
=> added React & Redux in TypeScript - Static Typing Guide

tips-and-best-practices.md
This PR removes an errant `)` in the redux link
=> Fixes redux architecture link name

react-tutorials.md
I also think it's no longer a free course :/
=> Updated link to React Fundamentals

README.md, javascript-resources.md
See discussion: https://github.com/reactiflux/reactiflux.com/pull/47#issuecomment-327840589
=> Fixed *Eric Elliott's Essential Javascript Links* 404 link

functional-programming.md
Changed the link to point to a wayback machine one.
=> Changed 'Understanding Programmatic Side Effects's link

react-component-patterns.md
=> Fix invisible anchor tags

react-component-composition.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
=> add React Composition Patterns from the Ground Up

redux-tutorials.md
=> Link to the original url

react-tutorials.md
Just a simple broken link fix.
=> Fix broken link

react-performance.md
Second one is 2 links lower.
Not sure which description is better - so randomly removed first one
```
**React is Slow, React is Fast: Optimizing React Apps in Practice** 
https://medium.com/dailyjs/react-is-slow-react-is-fast-optimizing-react-apps-in-practice-394176a11fba  
A clear and informative explanation covering multiple aspects of performance, including use of the Chrome DevTools flame graph for visualizing perf, extracting components and implementing `shouldComponentUpdate`, connecting to Redux, and use of Recompose and Reselect to improve performance.
```
=> Removes duplicate link

react-performance.md
https://blog.vixlet.com/react-at-light-speed-78cd172a6411
Nothing on web.archive
=> Removes dead link to blog.vexlet.com

javascript-resources.md
Domain has been changed and link is not working anymore.
- **Gentle Explanation of `this` keyword in Javascript**  
-  http://rainsoft.io/gentle-explanation-of-this-in-javascript/  
+  https://dmitripavlutin.com/gentle-explanation-of-this-in-javascript/ 
- **When 'not' to use arrow functions**  
-  http://rainsoft.io/when-not-to-use-arrow-functions-in-javascript/  
+ https://dmitripavlutin.com/when-not-to-use-arrow-functions-in-javascript/
=> Link fixed

react-component-patterns.md
Followed formatting instructions ✅
=> Added link for "Component Communication" section

react-implementation.md
Deep dive into the React programming model from first principles from React's lead developer (aka *Gold*)
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
=> Add Dan Abramov's React as a UI Runtime article

webpack-tutorials.md
the links is createapp.dev. It seems to help lots of people learn webpack!
=> added link to webpack configuration utility

react-tutorials.md
Please follow the existing formatting for each entry.  In order to get newlines without paragraph breaks, each entry should have two spaces at the end of the line after both the URL and the title.  Also, two-space indents before the URL and the description.  Example:
```markdown
- **Link Title**<space><space>  
<space><space>http://example.com<space><space>  
<space><space>Link description here
```
Result:
- **Link Title**  
http://example.com  
Link description here
Please do _not_ strip whitespace for existing entries!
=>  Replace the old facebook.github.io react doc links
